# ===============================
# PotionFood CONFIG
# ===============================

potion:
  # максимальна кількість використань зілля в крафті
  max-uses: 16

  # формат лору
  lore-format: "&7{%used%/%max%}"

# Список ефектів, які заборонено додавати в їжу
blacklist:
  - WITHER
  - BAD_OMEN
  - LEVITATION
  - HARM              # Миттєва шкода (Instant Damage)

messages:
  potion-empty: "&cЗілля закінчилося"
  potion-blacklisted: "&cЦе зілля заборонене"
  potion-already-drank: "&cЗілля закінчилося"
